FROM nginx:alpine

# Remove default config and web files
RUN rm -rf /etc/nginx/conf.d/* /usr/share/nginx/html/*

# Copy static files from public folder
COPY . /usr/share/nginx/html/

# Copy custom config
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
